import type { MetadataRoute } from "next";

/**
 * The web app manifest, for when Campivo is installed to a home screen.
 *
 * Next serves this at /manifest.webmanifest and links it from every page, so
 * the layout needs no change. The icons are the same mark as the favicon,
 * generated by `npm run icons`.
 *
 * `purpose: "maskable"` on the 512 tells Android it may crop the icon to
 * whatever shape the launcher uses. That is safe here because the mark is a
 * centred book on a full-bleed tile with generous margin — a circular mask
 * takes only tile, never the book. The 192 is left `"any"` so a launcher that
 * does not mask still gets the artwork undisturbed.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Campivo",
    short_name: "Campivo",
    description:
      "One place for your subjects, assignments, exams, timetable, attendance, marks and study progress.",
    start_url: "/",
    display: "standalone",
    // Matches --background and --primary in globals.css, so the splash screen
    // and address bar are the app's own colours rather than browser defaults.
    background_color: "#fafcff",
    theme_color: "#455bcf",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
